// packages/react/src/components/FieldGroup/FieldGroup.tsx
import { type FieldsetHTMLAttributes, type ReactNode, useId } from 'react';

import styles from './FieldGroup.module.css';

export interface FieldGroupProps extends Omit<FieldsetHTMLAttributes<HTMLFieldSetElement>, 'id'> {
  /** Group heading, rendered as the fieldset's `<legend>`. */
  label: string;
  /** Helper text shown below the label. Hidden when `error` is set. */
  helperText?: string;
  /**
   * Error message shown below the label in place of `helperText`.
   * Announced via `role="alert"` when it appears.
   */
  error?: string;
  /** Arbitrary field content — checkboxes, radios, a custom composite field, etc. */
  children?: ReactNode;
  /** Explicit id. Auto-generated when omitted. */
  id?: string;
}

/**
 * Generic form-field grouping with a shared label, help text, and error
 * message, for arbitrary fields outside a `BoxedList`.
 *
 * `PreferencesGroup` is scoped specifically to wrapping settings rows inside
 * a `BoxedList` — use `FieldGroup` for a plain `<fieldset>`/`<legend>`
 * grouping around any set of related form controls (e.g. a `RadioButton`
 * group or several `Checkbox`es sharing one label and error), independent
 * of the settings-page layout.
 *
 * Renders a native `<fieldset>`, so `disabled` automatically disables every
 * descendant form control for free — no need to thread it through manually.
 */
export const FieldGroup = ({
  label,
  helperText,
  error,
  id: idProp,
  className,
  children,
  ...props
}: FieldGroupProps) => {
  const autoId = useId();
  const id = idProp ?? autoId;
  const helpId = `${id}-help`;

  return (
    <fieldset
      id={id}
      aria-describedby={error || helperText ? helpId : undefined}
      className={[styles.group, className].filter(Boolean).join(' ')}
      {...props}
    >
      <legend className={styles.legend}>{label}</legend>

      {(error || helperText) && (
        <span
          id={helpId}
          role={error ? 'alert' : undefined}
          className={[styles.hint, error ? styles.errorHint : null].filter(Boolean).join(' ')}
        >
          {error ?? helperText}
        </span>
      )}

      <div className={styles.content}>{children}</div>
    </fieldset>
  );
};

// packages/web-components/src/field-group.ts
import { defineCustomElement, ensureId, HTMLElementBase } from './internal/dom';

const FIELDSET_SELECTOR = '[data-slot="field-group-fieldset"]';
const LEGEND_SELECTOR = '[data-slot="field-group-legend"]';
const HINT_SELECTOR = '[data-slot="field-group-hint"]';

/**
 * Generic form-field grouping with a shared label, help text, and error
 * message, for arbitrary fields outside a `gnome-boxed-list`.
 *
 * Wraps a real `<fieldset data-slot="field-group-fieldset">`/`<legend
 * data-slot="field-group-legend">` — same rationale as `gnome-highlight`
 * wrapping real `<mark>` and `gnome-kbd` wrapping real `<kbd>` — so
 * `disabled` disables every descendant form control for free via native
 * fieldset behavior, no need to thread it through each child manually.
 *
 * All original light-DOM children (the fields themselves — checkboxes,
 * radios, a custom composite field) are moved, once, into a generated
 * `<div data-slot="field-group-content">` inside the fieldset — same
 * adopt-existing-children technique as `gnome-expander-row`'s panel,
 * idempotent via checking the fieldset already exists as a direct child
 * before rebuilding.
 */
export class GnomeFieldGroupElement extends HTMLElementBase {
  static readonly observedAttributes = ['disabled', 'error', 'helper-text', 'label'];

  #connected = false;
  #fieldset: HTMLFieldSetElement | null = null;

  connectedCallback() {
    this.#connected = true;
    this.#wrapFieldset();
    this.#syncState();
  }

  attributeChangedCallback() {
    if (this.#connected) {
      this.#syncState();
    }
  }

  get label() {
    return this.getAttribute('label') ?? '';
  }

  set label(value: string) {
    this.setAttribute('label', value);
  }

  get helperText() {
    return this.getAttribute('helper-text') ?? '';
  }

  set helperText(value: string) {
    if (value) {
      this.setAttribute('helper-text', value);
    } else {
      this.removeAttribute('helper-text');
    }
  }

  get error() {
    return this.getAttribute('error') ?? '';
  }

  set error(value: string) {
    if (value) {
      this.setAttribute('error', value);
    } else {
      this.removeAttribute('error');
    }
  }

  get disabled() {
    return this.hasAttribute('disabled');
  }

  set disabled(value: boolean) {
    this.toggleAttribute('disabled', value);
  }

  #wrapFieldset() {
    const existing = this.querySelector<HTMLFieldSetElement>(FIELDSET_SELECTOR);

    if (existing && existing.parentElement === this) {
      this.#fieldset = existing;
      return;
    }

    const remaining = Array.from(this.children);

    const fieldset = document.createElement('fieldset');
    fieldset.dataset.slot = 'field-group-fieldset';

    const legend = document.createElement('legend');
    legend.dataset.slot = 'field-group-legend';
    fieldset.append(legend);

    const content = document.createElement('div');
    content.dataset.slot = 'field-group-content';

    for (const child of remaining) {
      content.append(child);
    }

    fieldset.append(content);
    this.append(fieldset);
    this.#fieldset = fieldset;
  }

  #syncState() {
    const fieldset = this.#fieldset;

    if (!fieldset) {
      return;
    }

    const legend = fieldset.querySelector<HTMLElement>(LEGEND_SELECTOR);

    if (legend && legend.textContent !== this.label) {
      legend.textContent = this.label;
    }

    if (fieldset.disabled !== this.disabled) {
      fieldset.disabled = this.disabled;
    }

    this.#syncHint(fieldset);
  }

  #syncHint(fieldset: HTMLFieldSetElement) {
    const { error, helperText } = this;
    const text = error || helperText;
    let hint = fieldset.querySelector<HTMLElement>(HINT_SELECTOR);

    if (!text) {
      hint?.remove();

      if (fieldset.hasAttribute('aria-describedby')) {
        fieldset.removeAttribute('aria-describedby');
      }

      return;
    }

    if (!hint) {
      hint = document.createElement('span');
      hint.dataset.slot = 'field-group-hint';
      fieldset.querySelector<HTMLElement>(LEGEND_SELECTOR)?.after(hint);
    }

    if (hint.textContent !== text) {
      hint.textContent = text;
    }

    hint.toggleAttribute('data-error', Boolean(error));

    if (error) {
      hint.setAttribute('role', 'alert');
    } else if (hint.hasAttribute('role')) {
      hint.removeAttribute('role');
    }

    const hintId = ensureId(hint, 'gnome-field-group-hint');

    if (fieldset.getAttribute('aria-describedby') !== hintId) {
      fieldset.setAttribute('aria-describedby', hintId);
    }
  }
}

export function registerGnomeFieldGroup() {
  defineCustomElement('gnome-field-group', GnomeFieldGroupElement);
}

registerGnomeFieldGroup();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-field-group': GnomeFieldGroupElement;
  }
}
