// packages/web-components/src/toolbar.ts
import { defineCustomElement, HTMLElementBase } from './internal/dom';

/**
 * Horizontal action bar following the libadwaita `.toolbar` style class.
 *
 * Pure CSS host — no attributes, no lifecycle logic. Provides the standard
 * 6px padding/gap for rows of flat or raised buttons in header bars, action
 * bars, and generic tool rows. Consumer-authored children (`gnome-button`,
 * `gnome-linked-group`, `gnome-dropdown`, `gnome-divider`/`gnome-separator`,
 * or anything else) render directly, in DOM order — same as the React
 * version, which never sets a `role` and expects the consumer to place
 * whatever controls belong there. Use a plain `flex: 1` filler `<div>`
 * between leading and trailing groups to push trailing items to the end
 * (mirrors the React version's `<Spacer />`).
 */
export class GnomeToolbarElement extends HTMLElementBase {}

export function registerGnomeToolbar() {
  defineCustomElement('gnome-toolbar', GnomeToolbarElement);
}

registerGnomeToolbar();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-toolbar': GnomeToolbarElement;
  }
}

// packages/react/src/components/Toolbar/Toolbar.tsx
import type { HTMLAttributes, ReactNode } from 'react';

import styles from './Toolbar.module.css';

export interface ToolbarProps extends HTMLAttributes<HTMLDivElement> {
  children: ReactNode;
}

/**
 * Horizontal action bar following the libadwaita `.toolbar` pattern.
 *
 * Provides 6 px padding and gap — the standard spacing for rows of flat
 * buttons in header bars, action bars, and tool rows. Place `<Spacer />`
 * between leading and trailing groups to push trailing items to the end.
 *
 * Use `<Button variant="flat">` or `<Button variant="raised">` inside:
 * - `flat` for buttons that blend into the bar background.
 * - `raised` for buttons that need explicit elevation within a flat context.
 *
 * @see https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/style-classes.html#toolbar-style-class
 */
export function Toolbar({ children, className, ...props }: ToolbarProps) {
  return (
    <div className={[styles.toolbar, className].filter(Boolean).join(' ')} {...props}>
      {children}
    </div>
  );
}
