// packages/web-components/src/bin.ts
import { defineCustomElement, HTMLElementBase } from './internal/dom';

/**
 * Single-child container with no visual styling of its own — mirrors
 * `AdwBin` and `@gnome-ui/react`'s own `Bin`.
 *
 * Pure CSS host — no attributes, no lifecycle logic, no `role`. A custom
 * element defaults to `display: inline`, so the only rule this ships is
 * `display: block`, matching a plain `<div>` — everything else (size,
 * layout, chrome) is left entirely to the consumer's own styling. Unlike
 * `gnome-toolbar` (which adds padding/gap), `Bin` adds nothing at all;
 * useful as a neutral base to apply layout or size constraints to without
 * introducing any chrome of its own.
 */
export class GnomeBinElement extends HTMLElementBase {}

export function registerGnomeBin() {
  defineCustomElement('gnome-bin', GnomeBinElement);
}

registerGnomeBin();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-bin': GnomeBinElement;
  }
}

// packages/react/src/components/Bin/Bin.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface BinProps extends HTMLAttributes<HTMLDivElement> {
  /** Single child. */
  children?: ReactNode;
}

/**
 * Single-child container with no visual styling.
 *
 * A transparent wrapper that constrains its content to one child while
 * forwarding all HTML div attributes. Useful as a base for custom components
 * that need a neutral container — e.g. to apply layout or size constraints
 * without introducing visual chrome.
 *
 * Mirrors `AdwBin`.
 *
 * @see https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Bin.html
 */
export const Bin = ({ children, ...props }: BinProps) => {
  return <div {...props}>{children}</div>;
};
