// packages/web-components/src/separator.ts
import { defineCustomElement, HTMLElementBase } from './internal/dom';

export type GnomeSeparatorOrientation = 'horizontal' | 'vertical';

/**
 * Thin dividing line that separates groups of content.
 *
 * Unlike the React version — which renders a semantic `<hr>` for the
 * horizontal case and a `<div role="separator">` for the vertical one — a
 * custom element is always a single fixed tag, so the host itself manages
 * `role="separator"` and `aria-orientation` for both orientations. Color is
 * driven entirely by design tokens and adapts to dark mode automatically.
 */
export class GnomeSeparatorElement extends HTMLElementBase {
  static readonly observedAttributes = ['orientation'];

  #connected = false;

  connectedCallback() {
    this.#connected = true;

    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'separator');
    }

    this.#syncState();
  }

  attributeChangedCallback() {
    if (this.#connected) {
      this.#syncState();
    }
  }

  get orientation(): GnomeSeparatorOrientation {
    return this.getAttribute('orientation') === 'vertical' ? 'vertical' : 'horizontal';
  }

  set orientation(value: GnomeSeparatorOrientation) {
    this.setAttribute('orientation', value);
  }

  #syncState() {
    const { orientation } = this;

    this.dataset.orientation = orientation;

    if (orientation === 'vertical') {
      this.setAttribute('aria-orientation', 'vertical');
    } else {
      this.removeAttribute('aria-orientation');
    }
  }
}

export function registerGnomeSeparator() {
  defineCustomElement('gnome-separator', GnomeSeparatorElement);
}

registerGnomeSeparator();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-separator': GnomeSeparatorElement;
  }
}

// packages/react/src/components/Separator/Separator.tsx
import type { HTMLAttributes } from 'react';

import styles from './Separator.module.css';

export type SeparatorOrientation = 'horizontal' | 'vertical';

export interface SeparatorProps extends HTMLAttributes<HTMLHRElement> {
  /** Direction of the dividing line. Defaults to `"horizontal"`. */
  orientation?: SeparatorOrientation;
}

/**
 * Thin dividing line that separates groups of content.
 *
 * Renders as `<hr>` (horizontal) or a `<div role="separator">` (vertical).
 * Color is driven entirely by design tokens and adapts to dark mode automatically.
 *
 * @see https://developer.gnome.org/hig/patterns/containers.html
 */
export function Separator({ orientation = 'horizontal', className, ...props }: SeparatorProps) {
  const classes = [
    styles.separator,
    orientation === 'vertical' ? styles.vertical : styles.horizontal,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  if (orientation === 'vertical') {
    return (
      <div
        role="separator"
        aria-orientation="vertical"
        className={classes}
        {...(props as HTMLAttributes<HTMLDivElement>)}
      />
    );
  }

  return <hr className={classes} {...props} />;
}
