// packages/web-components/src/tab-bar.ts
import { defineCustomElement, HTMLElementBase } from './internal/dom';

const TAB_SELECTOR = '[role="tab"]';
const SCROLL_START_SELECTOR = '[data-slot="tab-bar-scroll-start"]';
const SCROLL_END_SELECTOR = '[data-slot="tab-bar-scroll-end"]';

function isDisabled(tab: HTMLElement) {
  return (
    (tab instanceof HTMLButtonElement && tab.disabled) ||
    tab.getAttribute('aria-disabled') === 'true'
  );
}

function createScrollButton(
  slot: 'tab-bar-scroll-start' | 'tab-bar-scroll-end',
  label: string,
): HTMLButtonElement {
  const button = document.createElement('button');

  button.type = 'button';
  button.dataset.slot = slot;
  button.setAttribute('aria-label', label);
  button.hidden = true;

  const icon = document.createElement('span');

  icon.dataset.slot = 'tab-bar-scroll-icon';
  icon.setAttribute('aria-hidden', 'true');
  button.append(icon);

  return button;
}

/**
 * Horizontal tab list (`role="tablist"`).
 *
 * Requires descendants marked `role="tab"` — real `<button>`s recommended.
 * Same division of responsibility as `@gnome-ui/react`'s `TabBar`: the host
 * only manages roving-tabindex keyboard navigation (Left/Right/Home/End
 * moves focus, mirroring the offset/edge navigation shape in
 * `gnome-menu`'s keydown handler); it does not create tabs, change
 * `aria-selected`, or manage panel visibility — that stays with the
 * consumer, same as React.
 *
 * The host mirrors `aria-selected` onto `tabIndex` the same way
 * `gnome-radio-group` mirrors native `checked`: whichever tab has
 * `aria-selected="true"` becomes the roving-tabindex stop; if none does,
 * the first enabled tab is.
 *
 * The host itself is the scrollable element (`overflow-x: auto`, its
 * scrollbar hidden via CSS), so touch users can already swipe to reach
 * overflowing tabs — but nothing told a mouse/trackpad user, or anyone who
 * hasn't tried swiping, that there was more to see. Two host-generated
 * buttons (`[data-slot="tab-bar-scroll-start"]`/`-end`, `position: sticky`
 * to the host's own edges so they never scroll away with the content they
 * control) fade in only while there's genuinely more in that direction —
 * mirrors `@gnome-ui/react`'s `TabBar`, same `scrollLeft`/`scrollWidth`
 * math and the same RTL handling (`scrollLeft` ranges `[-max, 0]` in RTL
 * per the modern cross-browser convention, `[0, max]` in LTR — "forward"
 * flips sign, not meaning). Unlike `expander`'s host-generated header,
 * these don't move or wrap the consumer's own `[role="tab"]` children at
 * all — sticky positioning alone keeps them pinned without needing a
 * generated scroll wrapper around content the consumer still owns.
 */
export class GnomeTabBarElement extends HTMLElementBase {
  #observer: MutationObserver | null = null;
  #resizeObserver: ResizeObserver | null = null;
  #scrollStart: HTMLButtonElement | null = null;
  #scrollEnd: HTMLButtonElement | null = null;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'tablist');
    }

    this.addEventListener('keydown', this.#handleKeyDown);
    this.#wrapScrollButtons();
    this.#syncTabIndexes();
    this.#observeTabs();

    this.addEventListener('scroll', this.#updateScrollButtons, { passive: true });

    if (typeof ResizeObserver !== 'undefined') {
      this.#resizeObserver = new ResizeObserver(this.#updateScrollButtons);
      this.#resizeObserver.observe(this);
    }

    this.#updateScrollButtons();
  }

  disconnectedCallback() {
    this.removeEventListener('keydown', this.#handleKeyDown);
    this.removeEventListener('scroll', this.#updateScrollButtons);
    this.#observer?.disconnect();
    this.#observer = null;
    this.#resizeObserver?.disconnect();
    this.#resizeObserver = null;
  }

  get inline() {
    return this.hasAttribute('inline');
  }

  set inline(value: boolean) {
    this.toggleAttribute('inline', value);
  }

  #tabs() {
    return Array.from(this.querySelectorAll<HTMLElement>(TAB_SELECTOR));
  }

  #enabledTabs() {
    return this.#tabs().filter((tab) => !isDisabled(tab));
  }

  #wrapScrollButtons() {
    let start = this.querySelector<HTMLButtonElement>(SCROLL_START_SELECTOR);

    if (!start || start.parentElement !== this) {
      start = createScrollButton('tab-bar-scroll-start', 'Scroll to previous tabs');
      this.prepend(start);
    }

    start.addEventListener('click', this.#handleScrollStartClick);
    this.#scrollStart = start;

    let end = this.querySelector<HTMLButtonElement>(SCROLL_END_SELECTOR);

    if (!end || end.parentElement !== this) {
      end = createScrollButton('tab-bar-scroll-end', 'Scroll to next tabs');
      this.append(end);
    }

    end.addEventListener('click', this.#handleScrollEndClick);
    this.#scrollEnd = end;
  }

  #handleScrollStartClick = () => this.#scrollByPage(false);
  #handleScrollEndClick = () => this.#scrollByPage(true);

  /** `forward` moves toward later tabs, `backward` toward earlier ones — independent of LTR/RTL sign conventions. */
  #scrollByPage(forward: boolean) {
    const rtl = getComputedStyle(this).direction === 'rtl';
    const step = this.clientWidth * 0.8;
    const towardPositive = forward !== rtl;
    const reducedMotion =
      typeof window.matchMedia === 'function' &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    this.scrollBy({
      left: towardPositive ? step : -step,
      behavior: reducedMotion ? 'instant' : 'smooth',
    });
  }

  #updateScrollButtons = () => {
    // Modern engines agree `scrollLeft` ranges `[0, max]` in LTR and
    // `[-max, 0]` in RTL — its absolute distance from zero is the actual
    // scroll offset regardless of which one applies.
    const maxScroll = Math.max(0, this.scrollWidth - this.clientWidth);
    const scrolled = Math.min(maxScroll, Math.abs(this.scrollLeft));

    if (this.#scrollStart) {
      this.#scrollStart.hidden = scrolled <= 1;
    }

    if (this.#scrollEnd) {
      this.#scrollEnd.hidden = maxScroll - scrolled <= 1;
    }
  };

  #observeTabs() {
    this.#observer?.disconnect();
    this.#observer = new MutationObserver(() => {
      this.#syncTabIndexes();
      this.#updateScrollButtons();
    });
    this.#observer.observe(this, {
      attributes: true,
      attributeFilter: ['aria-disabled', 'aria-selected', 'disabled', 'role'],
      childList: true,
      subtree: true,
    });
  }

  #syncTabIndexes() {
    const tabs = this.#tabs();
    const selected = tabs.find(
      (tab) => tab.getAttribute('aria-selected') === 'true' && !isDisabled(tab),
    );
    const [firstEnabled] = this.#enabledTabs();
    const rovingStop = selected ?? firstEnabled;

    for (const tab of tabs) {
      tab.tabIndex = tab === rovingStop ? 0 : -1;
    }
  }

  #handleKeyDown = (event: KeyboardEvent) => {
    if (!(event.target instanceof Element)) {
      return;
    }

    const currentTab = event.target.closest<HTMLElement>(TAB_SELECTOR);

    if (!currentTab) {
      return;
    }

    const tabs = this.#enabledTabs();

    if (tabs.length === 0) {
      return;
    }

    const activeIndex = tabs.indexOf(currentTab);
    let nextIndex: number;

    if (event.key === 'ArrowRight') {
      nextIndex = activeIndex === -1 ? 0 : (activeIndex + 1) % tabs.length;
    } else if (event.key === 'ArrowLeft') {
      nextIndex =
        activeIndex === -1 ? tabs.length - 1 : (activeIndex - 1 + tabs.length) % tabs.length;
    } else if (event.key === 'Home') {
      nextIndex = 0;
    } else if (event.key === 'End') {
      nextIndex = tabs.length - 1;
    } else {
      return;
    }

    event.preventDefault();
    tabs[nextIndex]?.focus();
  };
}

export function registerGnomeTabBar() {
  defineCustomElement('gnome-tab-bar', GnomeTabBarElement);
}

registerGnomeTabBar();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-tab-bar': GnomeTabBarElement;
  }
}

// packages/react/src/components/Tabs/TabBar.tsx
import { usePrefersReducedMotion } from '@gnome-ui/hooks';
import { GoNext, GoNextRtl, GoPrevious, GoPreviousRtl } from '@gnome-ui/icons';
import {
  type HTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
  type RefObject,
  useEffect,
  useRef,
  useState,
} from 'react';

import { IconButton } from '@/components/IconButton';

import styles from './Tabs.module.css';

export interface TabBarProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode;
  /** Accessible label for the tab list. */
  'aria-label'?: string;
  /**
   * Removes the header-bar background so the tab bar blends into any surface.
   * Use when placing the bar inside a card, content area, or custom container.
   * Mirrors the `.inline` style class.
   */
  inline?: boolean;
}

interface ScrollState {
  atStart: boolean;
  atEnd: boolean;
  rtl: boolean;
}

/**
 * `overflow-x: auto` alone gives touch users a way to reach tabs past the
 * edge (native swipe), but nothing tells a mouse/trackpad user — or anyone
 * who hasn't tried swiping — that there's more to see, especially since the
 * scrollbar itself is hidden. This tracks whether `.list` currently overflows
 * in each direction and which way is genuinely "forward" per the DOM's own
 * resolved `direction`, so the buttons rendered from it never have to guess.
 */
function useTabListScrollState(listRef: RefObject<HTMLDivElement | null>) {
  const [state, setState] = useState<ScrollState>({ atStart: true, atEnd: false, rtl: false });

  useEffect(() => {
    const list = listRef.current;

    if (!list) {
      return;
    }

    const update = () => {
      const rtl = getComputedStyle(list).direction === 'rtl';
      // Modern engines agree `scrollLeft` ranges `[0, max]` in LTR and
      // `[-max, 0]` in RTL — its absolute distance from zero is the actual
      // scroll offset regardless of which one applies.
      const maxScroll = Math.max(0, list.scrollWidth - list.clientWidth);
      const scrolled = Math.min(maxScroll, Math.abs(list.scrollLeft));

      setState({ atStart: scrolled <= 1, atEnd: maxScroll - scrolled <= 1, rtl });
    };

    update();
    list.addEventListener('scroll', update, { passive: true });

    let observer: ResizeObserver | undefined;
    if (typeof ResizeObserver !== 'undefined') {
      observer = new ResizeObserver(update);
      observer.observe(list);
    }

    return () => {
      list.removeEventListener('scroll', update);
      observer?.disconnect();
    };
    // Re-measure whenever the tab list's own content changes (tabs added,
    // removed, or renamed) — `ResizeObserver` alone only fires on a layout
    // size change, not e.g. a label edit that keeps `scrollWidth` identical
    // by coincidence.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [listRef.current?.children.length]);

  return state;
}

/**
 * Horizontal tab bar that holds `TabItem` elements.
 *
 * Manages roving-tabindex keyboard navigation (← → Home End).
 *
 * When tabs overflow the bar, a "previous"/"next" button fades in at
 * whichever edge still has more to reveal — `.list`'s own `overflow-x: auto`
 * already lets touch users swipe there directly, but its scrollbar is
 * hidden, so mouse/trackpad users and anyone who hasn't discovered the
 * swipe get an explicit, always-visible way in too. Each press scrolls by
 * 80% of the bar's own width (a "page" of tabs), snapped instantly instead
 * of animated under `prefers-reduced-motion`.
 *
 * @see https://developer.gnome.org/hig/patterns/nav/tabs.html
 */
export const TabBar = ({
  children,
  className,
  inline = false,
  'aria-label': ariaLabel = 'Tabs',
  ...props
}: TabBarProps) => {
  const listRef = useRef<HTMLDivElement>(null);
  const { atStart, atEnd, rtl } = useTabListScrollState(listRef);
  const reducedMotion = usePrefersReducedMotion();

  function handleKeyDown(e: KeyboardEvent<HTMLDivElement>) {
    const tabs = Array.from(
      listRef.current?.querySelectorAll<HTMLButtonElement>('[role=tab]:not(:disabled)') ?? [],
    );
    const { activeElement } = document;
    const idx = activeElement instanceof HTMLButtonElement ? tabs.indexOf(activeElement) : -1;

    if (idx === -1) {
      return;
    }

    let next = idx;
    if (e.key === 'ArrowRight') {
      next = (idx + 1) % tabs.length;
    } else if (e.key === 'ArrowLeft') {
      next = (idx - 1 + tabs.length) % tabs.length;
    } else if (e.key === 'Home') {
      next = 0;
    } else if (e.key === 'End') {
      next = tabs.length - 1;
    } else {
      return;
    }

    e.preventDefault();
    tabs[next].focus();
  }

  /** `forward` moves toward later tabs (`.scrollWidth`'s far end), `backward` toward earlier ones — independent of LTR/RTL sign conventions. */
  function scrollByPage(forward: boolean) {
    const list = listRef.current;

    if (!list) {
      return;
    }

    const step = list.clientWidth * 0.8;
    const towardPositive = forward !== rtl;

    list.scrollBy({
      left: towardPositive ? step : -step,
      behavior: reducedMotion ? 'instant' : 'smooth',
    });
  }

  return (
    <div
      className={[styles.bar, inline ? styles.inline : null, className].filter(Boolean).join(' ')}
      {...props}
    >
      {!atStart && (
        <span className={styles.scrollButton}>
          <IconButton
            icon={rtl ? GoNextRtl : GoPrevious}
            label="Scroll to previous tabs"
            variant="flat"
            size="sm"
            onClick={() => scrollByPage(false)}
          />
        </span>
      )}
      <div
        ref={listRef}
        role="tablist"
        aria-label={ariaLabel}
        className={styles.list}
        onKeyDown={handleKeyDown}
      >
        {children}
      </div>
      {!atEnd && (
        <span className={styles.scrollButton}>
          <IconButton
            icon={rtl ? GoPreviousRtl : GoNext}
            label="Scroll to next tabs"
            variant="flat"
            size="sm"
            onClick={() => scrollByPage(true)}
          />
        </span>
      )}
    </div>
  );
};
