// packages/web-components/src/kbd.ts
import { defineCustomElement, HTMLElementBase } from './internal/dom';

const SYMBOL_MAP: Record<string, string> = {
  ctrl: '⌃',
  control: '⌃',
  shift: '⇧',
  alt: '⌥',
  option: '⌥',
  super: '⊞',
  win: '⊞',
  cmd: '⌘',
  command: '⌘',
  meta: '⌘',
  up: '↑',
  down: '↓',
  left: '←',
  right: '→',
  enter: '↵',
  return: '↵',
  backspace: '⌫',
  delete: '⌦',
  escape: '⎋',
  esc: '⎋',
  tab: '⇥',
  space: '␣',
  pageup: '⇞',
  pagedown: '⇟',
  home: '⇱',
  end: '⇲',
};

const KEY_SELECTOR = '[data-slot="kbd-key"]';

/**
 * Standalone single key-cap for inline instructional text (e.g. `Press
 * <gnome-kbd>Enter</gnome-kbd> to continue`).
 *
 * The key name is authored as plain light-DOM text — same as the native
 * `<kbd>` element — captured once on first connect into an internal
 * `#rawKey` so later re-renders (e.g. toggling `raw`) work from the
 * original name rather than from a symbol this component already
 * substituted in. Set the `key` property instead of `.textContent` for
 * programmatic updates after the initial render.
 *
 * Wraps a real `<kbd data-slot="kbd-key">` — same rationale as
 * `gnome-highlight` wrapping real `<mark>` elements — so the visible key
 * cap keeps genuine `<kbd>` semantics rather than relying on a custom
 * element tag alone.
 *
 * Common key names are normalised to their Unicode symbol unless `raw` is
 * set — mirrors `@gnome-ui/react`'s `Kbd`, which defaults `symbols` to
 * `true`. When a symbol is substituted, the original name moves to
 * `aria-label` (on the inner `<kbd>`) so assistive tech still announces
 * "Enter" rather than "↵".
 */
export class GnomeKbdElement extends HTMLElementBase {
  static readonly observedAttributes = ['raw'];

  #connected = false;
  #captured = false;
  #rawKey = '';

  connectedCallback() {
    if (!this.#captured) {
      this.#rawKey = (this.textContent ?? '').trim();
      this.#captured = true;
    }

    this.#connected = true;
    this.#syncContent();
  }

  attributeChangedCallback() {
    if (this.#connected) {
      this.#syncContent();
    }
  }

  get key() {
    return this.#rawKey;
  }

  set key(value: string) {
    this.#rawKey = value;
    this.#captured = true;

    if (this.#connected) {
      this.#syncContent();
    }
  }

  get symbols() {
    return !this.hasAttribute('raw');
  }

  set symbols(value: boolean) {
    this.toggleAttribute('raw', !value);
  }

  #syncContent() {
    const { key, symbols } = this;
    const display = symbols ? (SYMBOL_MAP[key.toLowerCase()] ?? key) : key;
    const label = display !== key ? key : null;

    let keyEl = this.querySelector<HTMLElement>(KEY_SELECTOR);

    if (!keyEl) {
      this.textContent = '';
      keyEl = document.createElement('kbd');
      keyEl.dataset.slot = 'kbd-key';
      this.append(keyEl);
    }

    if (keyEl.textContent !== display) {
      keyEl.textContent = display;
    }

    if (label) {
      if (keyEl.getAttribute('aria-label') !== label) {
        keyEl.setAttribute('aria-label', label);
      }
    } else if (keyEl.hasAttribute('aria-label')) {
      keyEl.removeAttribute('aria-label');
    }
  }
}

export function registerGnomeKbd() {
  defineCustomElement('gnome-kbd', GnomeKbdElement);
}

registerGnomeKbd();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-kbd': GnomeKbdElement;
  }
}

// packages/react/src/components/Kbd/Kbd.tsx
import type { HTMLAttributes } from 'react';

import styles from './Kbd.module.css';

export interface KbdProps extends Omit<HTMLAttributes<HTMLElement>, 'children'> {
  /**
   * The key name (e.g. `"Enter"`, `"Esc"`, `"A"`, `"Ctrl"`).
   *
   * Common key names are normalised to their Unicode symbol when `symbols`
   * is `true` (the default) — see `symbols` for the full mapping.
   */
  children: string;
  /**
   * Normalise common key names to their Unicode symbol (e.g. `"Enter"` → `↵`).
   * Matches the same mapping used by `ShortcutLabel`. Defaults to `true`.
   */
  symbols?: boolean;
}

const SYMBOL_MAP: Record<string, string> = {
  ctrl: '⌃',
  control: '⌃',
  shift: '⇧',
  alt: '⌥',
  option: '⌥',
  super: '⊞',
  win: '⊞',
  cmd: '⌘',
  command: '⌘',
  meta: '⌘',
  up: '↑',
  down: '↓',
  left: '←',
  right: '→',
  enter: '↵',
  return: '↵',
  backspace: '⌫',
  delete: '⌦',
  escape: '⎋',
  esc: '⎋',
  tab: '⇥',
  space: '␣',
  pageup: '⇞',
  pagedown: '⇟',
  home: '⇱',
  end: '⇲',
};

/**
 * Standalone single key-cap for inline instructional text
 * (e.g. `press <Kbd>Enter</Kbd> to continue`).
 *
 * Complements `ShortcutLabel`, which only renders full `+`-delimited
 * combos (`"Ctrl+S"`) and doesn't expose its per-key styling on its own.
 * Use `Kbd` when referencing a single key outside of a shortcut combo.
 */
export const Kbd = ({ children, symbols = true, className, ...props }: KbdProps) => {
  const display = symbols ? (SYMBOL_MAP[children.toLowerCase()] ?? children) : children;

  return (
    <kbd
      className={[styles.key, className].filter(Boolean).join(' ')}
      aria-label={display !== children ? children : undefined}
      {...props}
    >
      {display}
    </kbd>
  );
};
