// packages/web-components/src/bin.ts
import { defineCustomElement, HTMLElementBase } from './internal/dom';

/**
 * Single-child container with no visual styling of its own — mirrors
 * `AdwBin` and `@gnome-ui/react`'s own `Bin`.
 *
 * Pure CSS host — no attributes, no lifecycle logic, no `role`. A custom
 * element defaults to `display: inline`, so the only rule this ships is
 * `display: block`, matching a plain `<div>` — everything else (size,
 * layout, chrome) is left entirely to the consumer's own styling. Unlike
 * `gnome-toolbar` (which adds padding/gap), `Bin` adds nothing at all;
 * useful as a neutral base to apply layout or size constraints to without
 * introducing any chrome of its own.
 */
export class GnomeBinElement extends HTMLElementBase {}

export function registerGnomeBin() {
  defineCustomElement('gnome-bin', GnomeBinElement);
}

registerGnomeBin();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-bin': GnomeBinElement;
  }
}

// packages/react-native/src/components/Bin/Bin.tsx
import { forwardRef } from 'react';
import type { View, ViewProps } from 'react-native';
import { View as RNView } from 'react-native';

export type BinProps = ViewProps;

/**
 * Single-child container with no visual styling.
 *
 * A transparent wrapper that forwards all `View` props (and a ref to the
 * underlying `View`) straight through — useful as a neutral base for custom
 * components that need to apply layout or size constraints without
 * introducing any chrome of their own.
 *
 * Mirrors `AdwBin` and `@gnome-ui/react`'s own `Bin`. A plain RN `View`
 * already has no default visual styling (no background, no border), so
 * unlike the web port there's no CSS reset to strip — this is a pure
 * passthrough.
 *
 * @see https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Bin.html
 */
export const Bin = forwardRef<View, BinProps>(function Bin(props, ref) {
  return <RNView ref={ref} {...props} />;
});
